### ISSUE TITLE
Provide an ability to redirect on specified URL after fb login popup close.

### ISSUE THREAD

**Issue by Ivan31415** [splix/grails-spring-security-facebook#24]
In server-side authentication (via OAuth Dialog) now, it seems that spring-security-facebook allways redirects on '/' after its '/j_spring_security_facebook_check' callback. It will be cool to have this url be configurable.

Example simlpe scenario:

We have site with 3 pages - index, help, about. Each page has fb login button. Press fb login on any page -> OAuth Dialog opens. Press "go to App".
expexted result - redirect on page, where fb login was pressed
actual result - redirect on /

target url confuguration can be done like attribute in facebookAuth:connect tag.

**Comment by kmacpher67** [comment]
This is a little old. apparently, alot old.  haha. Sorry for late pasting. I didn't see how this was resolved? 
* GRAILS 309 - spring-security-core-3.0.3,  Running with Spring Boot v1.2.6.RELEASE, Spring v4.1.7.RELEASE
I've used this feature in a previous version of spring-security & google indicates that at one time spring-security used  
`default-target-url="/home.htm" ` and I assume that you're just extending this feature. 
See this guys discusses it he screwed it up & beckwith has a posting regarding it too: 
https://dzone.com/articles/spring-security-default-target

I don't think Beckwith changed any of that in the 3.x upgrade, so we should be able to set a default-target-url value on on yml or properties:

```` 
successHandler.defaultTargetUrl
“/”
Default post-login URL if there is no saved request that triggered the login
````
I set this value in yml is it supported there? 
````
            successHandler:
                defaultTargetUrl: '/hello/index'
````
but my success url is still 
`:8080/#_=_`
