### ISSUE TITLE
Proble with org.grails.plugins:spring-security-facebook:0.14.5

### ISSUE THREAD

**Issue by cklins** [splix/grails-spring-security-facebook#98]
I have an application with:

Grails 2.1.1

org.grails.plugins:spring-security-facebook:0.14.5

org.grails.plugins:spring-security-core:2.0.0

The application ran without problems, but these days I get this error:

No access_token in response: {"access_token":"EAAG9xkFde9EBABKzeZBq0AmUKSwpkcCGVnNTSEMMNAKs95igb6ImD8kpQsrvXxwcQ0OkHlHuaK4EJ6cmMCv7HUFQwmc2pnZAfECQYkH6mEVHqtqbqXuPZCSDMpLmEv1qNX5ZAJ9eRaIZC5ZBOH5IezKrpm7hxEHyYZd","token_type":"bearer","expires_in":5183472}

i refer your code v19,  "Facebook api response format has changed in v2.3 from Url to JSON"

could you help modify the method **FacebookAccessToken requestAccessToken(String authUrl)**
in class FacebookAuthUtils as 

FacebookAccessToken requestAccessToken(String authUrl) {
        try {
            URL url = new URL(authUrl)
            def response = url.readLines().first()

            // Facebook api response format has changed in v2.3 from Url to JSON
            def slurper = new groovy.json.JsonSlurper()
            Map data = [:]
            data = (Map)slurper.parseText(response)

            /*String response = url.readLines().first()
            //println "AccessToken response: $response"
            Map data = [:]
            response.split('&').each { String part ->
                String[] kv = part.split('=')
                if (kv.length != 2) {
                    log.warn("Invalid response part: $part")
                } else {
                    data[kv[0]] = kv[1]
                }
            }*/
            FacebookAccessToken token = new FacebookAccessToken()
            if (data.access_token) {
                token.accessToken = data.access_token
            } else {
                log.error("No access_token in response: $response")
            }
            if (data.expires_in) {
                if (data.expires_in =~ /^\d+$/) {
                    token.expireAt = new Date(System.currentTimeMillis() + TimeUnit.SECONDS.toMillis(data.expires_in as Long))
                } else {
                    log.warn("Invalid 'expires' value: $data.expires_in")
                }
            } else {
                log.error("No expires in response: $response")
            }
            //log.debug("Got AccessToken: $token")
            return token
        } catch (IOException e) {
            //TODO process error response
            log.warn("Can't read data from Facebook", e)
            return null
        }
    }

Any ideas please....

thank you

cklin

**Comment by senty** [comment]
Hi,
can you please check if your problem is not related to this issue :
https://github.com/splix/grails-spring-security-facebook/issues/97

**Comment by senty** [comment]
Hi, please upgrade to version 0.19 - author of this plugin already fix it there :-)
